"""Render the mined corpus into human-readable markdown references.

    corpus/vocabulary.json -> corpus/MECHANISMS.md   (stats: functors, conditions, enums)
    corpus/lsx_index.json  -> corpus/LSX_SCHEMA.md   (LSX: node types, attributes, GUIDs)
"""
from __future__ import annotations

import json
from pathlib import Path

CORPUS = Path(__file__).resolve().parent.parent / "corpus"
V = json.loads((CORPUS / "vocabulary.json").read_text(encoding="utf-8"))
IDX = json.loads((CORPUS / "index.json").read_text(encoding="utf-8"))

out: list[str] = []
w = out.append

w("# BG3 shipped-stats corpus — mechanism reference")
w("")
w("*Generated by `tools/corpus_index.py` from the extracted game data at "
  "`C:\\Modding\\bg3_unpacked` (Patch 8 / HotFix 9). Every number below is a real "
  "count from the shipped files — nothing here is inferred or remembered.*")
w("")
w(f"**{len(IDX):,} entries** across {len(V['type_counts'])} entry types. "
  f"**{len(V['functors'])} distinct functors**, **{len(V['conditions'])} distinct "
  f"condition helpers**, **{len(V['valuelists'])} enums**.")
w("")

w("## Entry types")
w("")
w("| Type | Count |")
w("|---|---:|")
for t, c in V["type_counts"].items():
    w(f"| `{t}` | {c:,} |")
w("")

w("## Entity keywords — the leading-argument census")
w("")
w("A functor's first positional argument may be an entity token that redirects who "
  "the functor acts on. This is undocumented on Larian's official Functors page. "
  "Counts are real call sites.")
w("")
tot: dict[str, int] = {}
for r in V["leading_entity_args"]:
    tot[r["entity"]] = tot.get(r["entity"], 0) + r["count"]
w("| Entity token | Total uses | Most common functors |")
w("|---|---:|---|")
for ent, n in sorted(tot.items(), key=lambda kv: -kv[1]):
    fns = [r for r in V["leading_entity_args"] if r["entity"] == ent][:5]
    w(f"| `{ent}` | {n:,} | " + ", ".join(f'`{r["functor"]}` ({r["count"]})' for r in fns) + " |")
w("")

w("## Colon-prefix targeting tokens")
w("")
w("The other targeting mechanism: a bare uppercase token before a `:` at the start "
  "of a functor clause. Note how few of these there are — this is the complete set.")
w("")
w("| Prefix | Uses | Example entry |")
w("|---|---:|---|")
for r in V["prefixes"]:
    ex = r.get("example") or {}
    w(f'| `{r["token"]}:` | {r["count"]:,} | `{ex.get("entry","")}` |')
w("")

w("## Functors")
w("")
w("Every functor that appears anywhere in the shipped data, by frequency. "
  "`Where` lists the fields it is actually used in — a functor is only legal in the "
  "contexts vanilla uses it in.")
w("")
w("| Functor | Uses | Where | Example call site |")
w("|---|---:|---|---|")
for r in V["functors"]:
    ex = r.get("example") or {}
    where = ", ".join(f"`{k}`" for k in list(r["fields"])[:3])
    w(f'| `{r["name"]}` | {r["count"]:,} | {where} | `{ex.get("entry","")}` |')
w("")

w("## Condition helpers")
w("")
w("Everything callable from a `Conditions` / `TargetConditions` / `EnableCondition` / "
  "`SpellRoll` expression.")
w("")
w("| Helper | Uses | Where | Example entry |")
w("|---|---:|---|---|")
for r in V["conditions"]:
    ex = r.get("example") or {}
    where = ", ".join(f"`{k}`" for k in list(r["fields"])[:3])
    w(f'| `{r["name"]}` | {r["count"]:,} | {where} | `{ex.get("entry","")}` |')
w("")

w("## Fields by entry type")
w("")
w("Which fields each entry type actually carries, and how many entries use each. "
  "A field used by 3 entries out of 1,848 is an edge case; one used by 1,800 is "
  "effectively mandatory.")
w("")
for t, fields in sorted(V["fields_by_type"].items(), key=lambda kv: -len(kv[1])):
    w(f"### `{t}`  ({V['type_counts'].get(t, 0):,} entries, {len(fields)} distinct fields)")
    w("")
    w("| Field | Entries using it |")
    w("|---|---:|")
    for f, c in fields.items():
        w(f"| `{f}` | {c:,} |")
    w("")

w("## Enums (`ValueLists.txt`)")
w("")
w("The legal values for every enum-typed field. Guessing a value that isn't in "
  "these lists is how a stats entry silently fails to load.")
w("")
for name, vals in sorted(V["valuelists"].items()):
    if not vals:
        continue
    w(f"**`{name}`** — " + ", ".join(f"`{v}`" for v in vals))
    w("")

dest = CORPUS / "MECHANISMS.md"
dest.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {dest} ({len(out):,} lines)")

# ---------------------------------------------------------------------------
# LSX half of the corpus.
#
# Same reasoning as MECHANISMS.md: the JSON is derived and gitignored, this
# markdown is tracked so that diffing it across a game patch shows Larian
# adding a node type or changing an attribute.
# ---------------------------------------------------------------------------
LSX_PATH = CORPUS / "lsx_index.json"
if not LSX_PATH.is_file():
    print(f"skipped LSX_SCHEMA.md - no {LSX_PATH} (run `py corpus_index.py`)")
    raise SystemExit(0)

L = json.loads(LSX_PATH.read_text(encoding="utf-8"))

# Node types that matter for gameplay modding. The corpus is dominated by
# material, texture and timeline nodes; listing all 637 would bury the useful
# ones. Everything is still in the JSON and reachable via --lsx-node.
INTERESTING = [
    "ClassDescription", "Progression", "ProgressionDescription", "SpellList",
    "PassiveList", "SkillList", "AbilityList", "ActionResource",
    "ActionResourceDefinition", "Feat", "FeatDescription", "Race", "Origin",
    "Background", "Tags", "flag", "LevelMapSeries", "GameObjects",
    "EffectInfo", "MultiEffectInfos", "ShortName", "Actor",
    "CharacterCreationAppearanceVisual", "EquipmentList",
]

out = []
w = out.append

w("# BG3 shipped-LSX corpus - node and GUID reference")
w("")
w("*Generated by `tools/corpus_index.py`. Covers both the files that ship as "
  "`.lsx` and the 8,228 `.lsf` + 483 `.lsfx` files converted to LSX with "
  "`Divine.exe -a convert-resources -i lsf -o lsx`. Every number is a real count "
  "from the shipped data.*")
w("")
w(f"**{len(L['files']):,} LSX files**, **{len(L['schema'])} distinct node types**, "
  f"**{len(L['defs']):,} GUIDs defined**, **{len(L['refs']):,} GUIDs referenced**.")
w("")
w("## How to query it")
w("")
w("```")
w("py tools/corpus_index.py --uuid <guid>        # what defines it, what points at it")
w("py tools/corpus_index.py --lsx-name Fighter   # GUID of a node by its Name")
w("py tools/corpus_index.py --lsx-node Progression   # which attributes it carries")
w("py tools/corpus_index.py --lsx-grep <regex>   # raw search over the LSX corpus")
w("py tools/corpus_index.py --identity-audit     # re-derive the GUID identity rule")
w("py tools/corpus_index.py --verify-lsx         # tokeniser vs ElementTree check")
w("```")
w("")

w("## Regions")
w("")
w("The top-level `<region id=...>` each node was found under.")
w("")
w("| Region | Nodes |")
w("|---|---:|")
for r, c in list(L["regions"].items())[:30]:
    w(f"| `{r or '(none)'}` | {c:,} |")
w("")

w("## Node types that matter for gameplay modding")
w("")
w("Attribute percentages are of that node type's instances. An attribute at "
  "100% is effectively mandatory; a low percentage is an optional field, and "
  "seeing it at 0.1% is a good sign you are about to use something Larian "
  "almost never uses.")
w("")
for nid in INTERESTING:
    rec = L["schema"].get(nid)
    if not rec:
        continue
    w(f"### `<node id=\"{nid}\">`  ({rec['count']:,} instances)")
    w("")
    w(f"*example: `{L['files'][rec['example']]}`*")
    w("")
    w("| Attribute | Type | Count | % |")
    w("|---|---|---:|---:|")
    for aid, a in rec["attrs"].items():
        pct = 100.0 * a["count"] / rec["count"]
        w(f"| `{aid}` | `{a['type']}` | {a['count']:,} | {pct:.1f}% |")
    w("")

w("## All node types by frequency")
w("")
w("| Node | Instances | Distinct attributes |")
w("|---|---:|---:|")
for nid, rec in list(L["schema"].items())[:120]:
    w(f"| `{nid}` | {rec['count']:,} | {len(rec['attrs'])} |")
w("")
w(f"*({len(L['schema'])} node types total; the rest are material, texture and "
  f"timeline internals. Query any of them with `--lsx-node`.)*")

dest = CORPUS / "LSX_SCHEMA.md"
dest.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {dest} ({len(out):,} lines)")
