"""Starter validator for FixtureBlade - generated by forge.py.

WHY THIS FILE EXISTS. An outside review of this framework (2026-08-25) found that
it "documents a strong validation regime, but the generated mod does not actually
receive a validator": build.ps1 called validation a gate, then printed
"validate.py not found - skipping" and packed anyway. A gate that is optional in
practice is not a gate, so every scaffolded mod now starts with this.

WHAT IT IS, HONESTLY. This checks LOCAL INVARIANTS ONLY - that the mod is
internally consistent. It CANNOT tell you a functor is real, that a status exists
in the game, or that a field is one the engine reads, because it does not look at
shipped game data. Those bugs cost a launch and a reroll to find, and the full
corpus-backed validator in a mature project catches them. Treat a clean run here
as "nothing is obviously self-contradictory", never as "this works".

    py tools/validate.py          # exit 1 on any ERROR
    py tools/validate.py --warn   # treat WARNs as failures too

Checks: XML parses; localisation handles declared; no duplicate UUIDs;
ClassDescription progression UUID matches every progression table; progression
passives exist; AddSpells targets a real spell list; spell-list entries exist;
spell resource costs resolve; spent resources are granted; `using` chains
terminate.
"""
from __future__ import annotations

import json
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ERR: list[str] = []
WARN: list[str] = []

# A floor, not a corpus. These are the vanilla resources a starter class is most
# likely to spend; anything else must be declared in ActionResourceDefinitions.lsx.
# If a real vanilla resource is missing here, add it - do not silence the check.
VANILLA_RESOURCES = {
    "ActionPoint", "BonusActionPoint", "ReactionActionPoint", "Movement",
    "SpellSlot", "KiPoint", "SuperiorityDie", "Rage", "SorceryPoint",
    "WildShape", "ChannelDivinity", "ChannelOath", "BardicInspiration",
    "LayOnHandsCharge", "ArcaneRecoveryPoint", "NaturalRecoveryPoint",
    "FungalInfestationCharge", "WarPriestActionPoint", "SneakAttack_Charge",
}


def err(msg: str) -> None:
    ERR.append(msg)


def warn(msg: str) -> None:
    WARN.append(msg)


def cfg() -> dict:
    f = ROOT / "forge.json"
    if not f.exists():
        err("forge.json missing - nothing can be located without it")
        return {}
    return json.loads(f.read_text(encoding="utf-8"))


def lsx_files() -> list[Path]:
    return sorted(ROOT.glob("Public/**/*.lsx")) + sorted(ROOT.glob("Mods/**/*.lsx"))


def stats_files() -> list[Path]:
    return sorted(ROOT.glob("Public/**/Stats/Generated/Data/*.txt"))


def parse_all() -> dict:
    trees = {}
    for f in lsx_files() + sorted(ROOT.glob("Localization/**/*.xml")):
        try:
            trees[f] = ET.parse(f)
        except ET.ParseError as e:
            err("{}: XML does not parse - {}".format(f.relative_to(ROOT), e))
    return trees


def attrs(tree, id_name):
    """Every <attribute id="..."> value in a parsed lsx."""
    return [a.get("value") for a in tree.iter("attribute") if a.get("id") == id_name]


def check_handles(trees) -> None:
    declared = set()
    for f, t in trees.items():
        if f.suffix == ".xml":
            declared.update(c.get("contentuid") for c in t.iter("content"))
    used = set()
    for f, t in trees.items():
        if f.suffix == ".lsx":
            for a in t.iter("attribute"):
                v = a.get("value") or ""
                if re.fullmatch(r"h[0-9a-f]{8,}\w*", v):
                    used.add(v)
    for f in stats_files():
        used.update(re.findall(r"\b(h[0-9a-f]{8}\w*)\b", f.read_text(encoding="utf-8")))
    for h in sorted(used - declared):
        err("localisation handle {} used but never declared".format(h))
    for h in sorted(declared - used):
        warn("localisation handle {} declared but never used".format(h))


def check_uuids(trees) -> None:
    seen = Counter()
    for f, t in trees.items():
        if f.suffix != ".lsx":
            continue
        for a in t.iter("attribute"):
            if (a.get("type") or "") == "guid" or a.get("id", "").endswith("UUID"):
                v = a.get("value") or ""
                if re.fullmatch(r"[0-9a-fA-F-]{36}", v):
                    seen[v] += 1
    # A UUID legitimately repeats when one record points at another, so only a
    # DEFINING collision matters: the same uuid as the identity of two records.
    ids = Counter()
    for f, t in trees.items():
        if f.suffix != ".lsx":
            continue
        for node in t.iter("node"):
            for a in node.findall("attribute"):
                if a.get("id") in ("UUID", "MapKey"):
                    ids[a.get("value")] += 1
    for u, n in ids.items():
        if n > 1 and u:
            err("UUID {} defines {} different records - references break unpredictably"
                .format(u, n))


def check_progressions(trees) -> None:
    table_ids, class_tables = set(), set()
    for f, t in trees.items():
        if f.suffix != ".lsx":
            continue
        if f.name == "ClassDescriptions.lsx":
            class_tables.update(v for v in attrs(t, "ProgressionTableUUID") if v)
        if f.name == "Progressions.lsx":
            table_ids.update(v for v in attrs(t, "TableUUID") if v)
    if class_tables and table_ids:
        for c in sorted(class_tables - table_ids):
            err("ClassDescriptions ProgressionTableUUID {} has no Progressions TableUUID - "
                "the subclass will appear and grant nothing".format(c))
        for p in sorted(table_ids - class_tables):
            warn("Progressions TableUUID {} is not referenced by any ClassDescription".format(p))
    elif not class_tables:
        err("no ProgressionTableUUID found in ClassDescriptions.lsx")


def check_passives_and_spells(trees) -> None:
    stats_text = {f: f.read_text(encoding="utf-8") for f in stats_files()}
    defined = set()
    for txt in stats_text.values():
        defined.update(re.findall(r'^new entry "([^"]+)"', txt, re.M))

    granted, spell_list_refs, costs, resource_grants = set(), set(), set(), set()
    for f, t in trees.items():
        if f.suffix != ".lsx" or f.name != "Progressions.lsx":
            continue
        for a in t.iter("attribute"):
            v = a.get("value") or ""
            if a.get("id") == "PassivesAdded":
                granted.update(x.strip() for x in v.split(";") if x.strip())
            if a.get("id") == "Selectors":
                spell_list_refs.update(re.findall(r"AddSpells\(([0-9a-fA-F-]{36})", v))
            if a.get("id") == "Boosts":
                resource_grants.update(re.findall(r"ActionResource\(([A-Za-z_]+)", v))

    for p in sorted(granted - defined):
        err('progression grants passive "{}" which no Passive.txt defines'.format(p))

    list_uuids, list_spells = set(), set()
    for f, t in trees.items():
        if f.suffix == ".lsx" and f.name == "SpellLists.lsx":
            list_uuids.update(v for v in attrs(t, "UUID") if v)
            for v in attrs(t, "Spells"):
                list_spells.update(x.strip() for x in (v or "").split(",") if x.strip())
    for u in sorted(spell_list_refs - list_uuids):
        err("AddSpells({}) references a spell list this mod does not define".format(u))
    for s in sorted(list_spells - defined):
        err('spell list contains "{}" which no stats file defines'.format(s))

    declared_res = set()
    for f, t in trees.items():
        if f.suffix == ".lsx" and "ActionResourceDefinitions" in f.name:
            declared_res.update(v for v in attrs(t, "Name") if v)
    for txt in stats_text.values():
        for m in re.findall(r'^data "UseCosts" "([^"]*)"', txt, re.M):
            for part in m.split(";"):
                name = part.split(":")[0].strip()
                if name and not name[0].isdigit():
                    costs.add(name)
    for c in sorted(costs):
        if c not in declared_res and c not in VANILLA_RESOURCES:
            err('spell costs "{}" which is neither a vanilla resource nor declared in '
                "ActionResourceDefinitions.lsx".format(c))
    for c in sorted(costs & declared_res):
        if c not in resource_grants:
            err('"{}" is spent by a spell and defined by this mod, but no progression '
                "grants it - the player can never pay the cost".format(c))


def check_using(trees) -> None:
    parents, entries = {}, set()
    for f in stats_files():
        txt = f.read_text(encoding="utf-8")
        cur = None
        for line in txt.splitlines():
            m = re.match(r'^new entry "([^"]+)"', line)
            if m:
                cur = m.group(1)
                entries.add(cur)
            m = re.match(r'^using "([^"]+)"', line)
            if m and cur:
                parents[cur] = m.group(1)
    for start in list(parents):
        seen, node = set(), start
        while node in parents:
            if node in seen:
                err('`using` chain starting at "{}" is a cycle'.format(start))
                break
            seen.add(node)
            node = parents[node]


def main() -> int:
    strict = "--warn" in sys.argv
    name = cfg().get("name", "?")
    trees = parse_all()
    if not ERR:
        check_handles(trees)
        check_uuids(trees)
        check_progressions(trees)
        check_passives_and_spells(trees)
        check_using(trees)

    print("validate - {} (starter: LOCAL invariants only, not game data)".format(name))
    for e in ERR:
        print("  ERROR  " + e)
    for w in WARN:
        print("  warn   " + w)
    print("\n{} error(s), {} warning(s)".format(len(ERR), len(WARN)))
    if ERR or (strict and WARN):
        return 1
    print("no self-contradictions found. This is NOT proof the mod works in game.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
